name: Checks
on:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 20"
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm