name: Code Check

on: 
  pull_request

env:
  LEFTHOOK: 0
  CI: true

permissions:
  actions: write
  contents: write

jobs:
  lint:
    name: 💅 Biome
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: 🦖 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: 🔻 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🏃 Run Node and NPM setup
        uses: ./.github/actions/setup-project

      - name: 👧 Lint check
        run: pnpm lint:ci
      
      - name: ✍️ Fix lint issues
        if: ${{ failure() }}
        run: |
          pnpm lint:fix
      
      - name: 💭 Get current branch name
        id: get_branch
        if: ${{ failure() }}
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        
      - name: 📥 Checkout current branch
        if: ${{ failure() }}
        run: git checkout ${{ steps.get_branch.outputs.BRANCH_NAME }}
        
      - name: 🔄 Commit changes
        if: ${{ failure() }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "fix(lint): safe errors" || echo "No changes to commit"
          git push

      - name: 🔄 Rerun Linter
        if: ${{ failure() }}  
        run: pnpm lint:ci